disabled_rules:
- unused_setter_value
- identifier_name
- type_body_length

excluded:
- Dependencies/
- ../FonttasticTools/Sources/Potrace.swift

function_parameter_count:
- 9
- 12

file_length:
- 700
- 1000